name: CI MLflow (Advanced)

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # 1. Start job
      - name: Set up job
        run: echo "Start CI workflow for MLflow (Advanced)"

      # 2. Checkout repo
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      # 3. Setup Python
      - name: Set up Python 3.10.19
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10.19
          use-mamba: true

      # 4. Check environment
      - name: Check Env
        shell: bash -l {0}
        run: |
          python --version
          conda list

      # 5. Install dependencies
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow dagshub

      # 6. Run MLflow Project (training)
      - name: Run MLflow Project
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8. Build Docker image from MLflow Model Registry
      - name: Build Docker Model
        shell: bash -l {0}
        run: |
          mlflow models build-docker \
            -m models:/Titanic-Advanced-Tuning/Production \
            -n ekasandy/titanic-mlflow:latest

      # 9. Push Docker image
      - name: Push Docker Image
        run: docker push ekasandy/titanic-mlflow:latest

      # 10. Complete
      - name: Complete job
        run: echo "CI MLflow Advanced job complete"
