name: CI MLflow Advanced

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install mlflow==2.18.0 dagshub scikit-learn pandas matplotlib

      - name: Run MLflow Project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        working-directory: ./MLProject  
        run: |
          mlflow run . --experiment-name Titanic-Advanced-Tuning

      - name: Get latest MLflow run_id
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/ekasandyaulia-lgtm/SMLS_Eka_Sandy_Aulia_Puspitasari.mlflow
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          RUN_ID=$(mlflow runs list --experiment-name Titanic-Advanced-Tuning --max-results 1 | tail -n 1 | awk '{print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest Run ID: $RUN_ID"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image from MLflow Model
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/ekasandyaulia-lgtm/SMLS_Eka_Sandy_Aulia_Puspitasari.mlflow
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow models build-docker \
            -m "runs:/${{ env.RUN_ID }}/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest" \
            --enable-mlserver

      - name: Push Docker Image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest"
