name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install MLflow & Dagshub
        run: |
          pip install mlflow==2.18.0 dagshub
      - name: Fix conda activation for MLflow
        run: |
          echo "MLFLOW_CONDA_HOME=/usr/share/miniconda" >> $GITHUB_ENV
          
      - name: Run MLflow Project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image from Latest Run
        run: |
          RUN_ID=$(mlflow runs list \
            --experiment-name Titanic-Advanced-Tuning \
            --max-results 1 \
            --output csv | tail -n 1 | cut -d',' -f1)

          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ekasandyaulia/titanic-mlflow:latest

      - name: Push Docker Image
        run: |
          docker push ekasandyaulia/titanic-mlflow:latest

      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: MLProject/artifacts/