name: CI MLflow (Advanced)

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Start job
        run: echo "Start CI workflow for MLflow (Advanced)"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10.19
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10.19
          use-mamba: true

      - name: Check Env
        shell: bash -l {0}
        run: |
          python --version
          conda list

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python Modelling_tunning.py

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Model
        shell: bash -l {0}
        run: |
          mlflow models build-docker \
            -m models:/Titanic-Advanced-Tuning/latest \
            -n ekasandy/titanic-mlflow:latest

      - name: Push Docker Image
        run: docker push ekasandy/titanic-mlflow:latest

      - name: Complete job
        run: echo "CI MLflow Advanced job complete"
