name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.18.0 dagshub scikit-learn pandas matplotlib seaborn

      - name: Run MLflow Project
        id: run_mlflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject --env-manager local

      - name: Get Latest RUN_ID
        id: get_run
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          RUN_ID=$(python -c "import os, mlflow; import pandas as pd; mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI']); r=mlflow.search_runs(order_by=['start_time DESC'], max_results=1); print(r.iloc[0].run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "RUN_ID is $RUN_ID"

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n ekasandyaulia/titanic-mlflow:latest --env-manager local

      - name: Push Docker Image
        run: |
          docker push ekasandyaulia/titanic-mlflow:latest

      - name: Download Training Artefacts
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mkdir -p MLProject/artifacts
          mlflow artifacts download --run-id $RUN_ID --artifact-path "model" -d MLProject/artifacts/model
          # Artefak manual (confusion matrix & feature importance)
          mlflow artifacts download --run-id $RUN_ID --artifact-path "artifacts" -d MLProject/artifacts/manual