name: CI MLflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          python-version: "3.12"

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow==2.18.0 dagshub

      - name: Run Modelling Tuning
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_REPO_OWNER: ${{ secrets.DAGSHUB_REPO_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python MLProject/Modelling_tunning.py --use-dagshub

      - name: Upload run_id
        uses: actions/upload-artifact@v4
        with:
          name: run-info
          path: run_info.txt

      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          RUN_ID=$(cat run_info.txt)
          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest \
            --enable-mlserver

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest