name: CI MLflow Advanced

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: titanic-mlflow
          auto-activate-base: false

      - name: retrain model via mlflow project
        shell: bash -l {0}
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --experiment-name Titanic-Advanced-Tuning

      - name: login docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build docker image from model registry
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/ekasandyaulia-lgtm/SMLS_Eka_Sandy_Aulia_Puspitasari.mlflow
        run: |
          mlflow models build-docker \
            -m "models:/TitanicModel/Production" \
            -n "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest" \
            --enable-mlserver

      - name: push docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest"
