name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install mlflow==2.18.0 dagshub scikit-learn pandas matplotlib seaborn

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject --env-manager local

      - name: Get Latest Run ID
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          RUN_ID=$(mlflow runs list \
            --experiment-name Titanic-Advanced-Tuning \
            --order-by attribute.start_time DESC \
            --max-results 1 \
            | awk 'NR==2 {print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ekasandyaulia/titanic-mlflow:latest \
            --env-manager local

      - name: Push Docker Image
        run: docker push ekasandyaulia/titanic-mlflow:latest

      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: artifacts/