name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install mlflow==2.18.0 scikit-learn pandas matplotlib seaborn

      - name: Run MLflow Project
        run: mlflow run MLProject

      - name: Get Latest Run ID
        run: |
          RUN_ID=$(ls -td mlruns/*/* | head -n 1 | awk -F'/' '{print $(NF-1)}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Using RUN_ID=$RUN_ID"

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n ekasandyaulia/titanic-mlflow:latest \
            --env-manager local

      - name: Push Docker Image
        run: docker push ekasandyaulia/titanic-mlflow:latest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: MLProject/artifacts/