name: CI MLflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: titanic-mlflow
          environment-file: MLProject/conda.yaml
          python-version: "3.12"
          auto-activate-base: false

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Modelling Tunning
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_REPO_OWNER: ${{ secrets.DAGSHUB_REPO_OWNER }}
          DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        working-directory: ./MLProject
        run: |
          python Modelling_tunning.py --mlflow-tracking-uri "$MLFLOW_TRACKING_URI" --use-dagshub

      - name: Upload run_id as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: run-info
          path: MLProject/run_info.txt

      - name: Login to Docker Hub
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image from MLflow Model
        if: success()
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          RUN_ID=$(cat MLProject/run_info.txt)
          echo "Run ID: $RUN_ID"
          mlflow models build-docker \
            -m "runs:/$RUN_ID/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest" \
            --enable-mlserver

      - name: Push Docker Image to Docker Hub
        if: success()
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/titanic-mlflow:latest"
