name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install --upgrade pip
          pip install mlflow==2.18.0 dagshub scikit-learn pandas matplotlib seaborn

      - env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: mlflow run MLProject --env-manager local

      - env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python - <<EOF
import os
import mlflow
from mlflow.tracking import MlflowClient
mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
client = MlflowClient()
runs = client.search_runs(experiment_ids=["0"], order_by=["start_time DESC"], max_results=1)
if not runs:
    raise Exception("❌ No runs found")
run_id = runs[0].info.run_id
with open(os.environ["GITHUB_ENV"], "a") as f:
    f.write(f"RUN_ID={run_id}\n")
print(f"✅ Latest RUN_ID={run_id}")
EOF

      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: |
          mlflow models build-docker -m runs:/$RUN_ID/model -n ekasandyaulia/titanic-mlflow:latest --env-manager local

      - run: docker push ekasandyaulia/titanic-mlflow:latest