name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.18.0 dagshub scikit-learn pandas matplotlib seaborn

      - name: Run MLflow Project
        id: run_mlflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "=== Menjalankan MLflow Project ==="
          mlflow run MLProject --env-manager local

      - name: Get Parent RUN_ID
        id: get_run
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "=== Mengambil Parent RUN_ID terbaru ==="
          RUN_ID=$(python -c "import os, mlflow; mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI']); r = mlflow.search_runs(filter_string='tags.mlflow.parentRunId IS NULL', order_by=['start_time DESC'], max_results=1); print(r.iloc[0].run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "RUN_ID is $RUN_ID"

      - name: Download Training Artefacts
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ekasandyaulia-lgtm
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "=== Download artefak MLflow ==="
          mkdir -p MLProject/artifacts/manual
          mkdir -p MLProject/artifacts/autolog
          mlflow artifacts download --run-id $RUN_ID --artifact-path "MLmodel" -d MLProject/artifacts/autolog
          mlflow artifacts download --run-id $RUN_ID --artifact-path "artifacts" -d MLProject/artifacts/manual

      - name: List artefak after MLflow run
        run: |
          echo "=== Artefak MLmodel (autolog) ==="
          ls -R MLProject/artifacts/autolog || echo "Folder autolog kosong"
          echo "=== Artefak manual ==="
          ls -R MLProject/artifacts/manual || echo "Folder manual kosong"

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          echo "=== Build Docker Image ==="
          mlflow models build-docker -m "runs:/$RUN_ID/MLmodel" -n ekasandyaulia/titanic-mlflow:latest --env-manager local

      - name: Push Docker Image
        run: |
          echo "=== Push Docker Image ke Docker Hub ==="
          docker push ekasandyaulia/titanic-mlflow:latest