name: CI MLflow

on:
  push:
    branches: ["main"]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Start CI workflow for MLflow"

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.10.19
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10.19
          use-mamba: true

      - name: Check Env
        shell: bash -l {0}
        run: |
          python --version
          conda list

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        shell: bash -l {0}
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject

      - name: Get latest MLflow run_id
        shell: bash -l {0}
        run: |
          echo "MLFLOW_RUN_ID=$(ls mlruns/0 | sort | tail -n 1)" >> $GITHUB_ENV

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            -m mlruns/0/*/artifacts/model \
            -n ekasandy/titanic-mlflow:latest

      - name: Tag Docker Image
        run: echo "Tagged Docker image"

      - name: Push Docker Image
        run: docker push ekasandy/titanic-mlflow:latest

      - name: Complete job
        run: echo "CI job complete"
